Added details to Spark section
madetech/data-101 pull request #15
Opened 2022-04-05 12:39 UTC by YasminMorshed

2022-04-06 09:35 UTC, tf75 commented on modules/core/Spark.md
> +Spark is a tool for managing and coordinating the execution of tasks on data across a cluster of computers. Apache Spark is written primarily in the Scala programming language. PySpark is an interfac
I would change this paragraph to this:
"Apache Spark is a multi-language engine for executing data engineering, data science, and machine learning on single-node machines or clusters. Apache Spark is written primarily in the Scala programming language. PySpark is an interface for Apache Spark in Python, which is used for real-time, large-scale data processing."

2022-04-06 09:35 UTC, tf75 commented on modules/core/Spark.md
> +Take a look at [PySpark's installation instructions](https://spark.apache.org/docs/latest/api/python/getting_started/install.html "PySpark's Installation Instructions").
This should link back to our installation instructions in setting up python environment

2022-04-06 09:35 UTC, tf75 commented on modules/core/Spark.md
> +If you are stuck on setting up the project, refer to the instructions on [this](https://github.com/databricks/Spark-The-Definitive-Guide "this") page.
The setting up python environment should be instruction enough to set this up? Have you gone through that page, do we need to add anything?

2022-04-06 15:58 UTC, AdamProbert requested changes

2022-04-06 15:58 UTC, AdamProbert commented on modules/core/Spark.md
> +Adding the code above will show us the explain plan, so you should see something like this:
Might be worth linking to some documentation on what an explain plan is

2022-04-06 15:58 UTC, AdamProbert commented on modules/core/Spark.md
> +6) Below is an example of querying using SQL against a dataframe:
```suggestion
6) Below is an example of querying using SQL against a DataFrame:
```

2022-04-06 15:58 UTC, AdamProbert commented on modules/core/Spark.md
> +How could you do this using just DataFrame code? Using `sqlWay.explain()` will also show how Spark will execute the query.
Might be useful showing the equivalent without sql?

2022-04-08 13:04 UTC, AdamProbert approved these changes
Great additions! Nice one Yasmin 🚀

2022-04-08 13:14 UTC, merged